### ISSUE TITLE
Error after FW update to moitessier_4.19.75_armhf

### ISSUE THREAD

**Issue by hwater** [mr-rooney/moitessier#1]
Hello,
 the installer gives an Error on kernel 
```
[    0.000000] Booting Linux on physical CPU 0x0
[    0.000000] Linux version 5.4.72-v7l+ (dom@buildbot) (gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)) #1356 SMP Thu Oct 22 13:57:51 BST 2020
[    0.000000] CPU: ARMv7 Processor [410fd083] revision 3 (ARMv7), cr=30c5383d

```
 and the install is incomplete (no /dev/moitessier.tty or .spi).

this is the message after firmware install:
### 
`GPIO sequence end

******************************************************************************************
FIRMWARE UPDATE SUCCESSFULL!!!
******************************************************************************************

insmod: ERROR: could not insert module ./moitessier_5.4.72-v7l+.ko: Invalid module format

******************************************************************************************
ERROR occured!!

Could not load "./moitessier_5.4.72-v7l+.ko".
******************************************************************************************

`

the same error after trying with shell command:
`cd ~/moitessier/flasher/ && sudo ./fw_update_moitessier -r`

I hope you will find an solution, many Greetings from Linz/Danube.
Holger

**Comment by mr-rooney** [comment]
Raspberry Pi changed the toolchain to compile the latest kernel version 5.4.72. The Moitessier sources need to be compiled with the same toolchain, otherwise module loading will fail. A new package will be available in the next days.

**Comment by hwater** [comment]
+++ thx for detailing the problem

**Comment by mr-rooney** [comment]
A new package can be downloaded at www.rooco.eu
